chat_client: chat_client.c
	gcc -o chat_client -std=c99 -Wall -O1 chat_client.c

chat_server: chat_server.c
	gcc -o chat_server -std=c99 -Wall -O1 chat_server.c

client: client.c
	gcc -o client -std=c99 -Wall -O1 client.c

server: server.c
	gcc -o server -std=c99 -Wall -O1 server.c

clean:
	rm chat_client
	rm chat_server
